# Generated by Django 4.2.3 on 2023-08-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='advertisements',
        ),
    ]
